//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.09 at 01:15:32 PM EST 
//


package com.bayer.integration.rest.polhis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BayerCommitmentLIHistoryAPIRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerCommitmentLIHistoryAPIRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BayerCommitmentLIHistoryAPI" type="{http://ecosys.net/api/BayerCommitmentLIHistoryAPI}BayerCommitmentLIHistoryAPIType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerCommitmentLIHistoryAPIRequestType", propOrder = {
    "bayerCommitmentLIHistoryAPI"
})
public class BayerCommitmentLIHistoryAPIRequestType {

    @XmlElement(name = "BayerCommitmentLIHistoryAPI")
    protected List<BayerCommitmentLIHistoryAPIType> bayerCommitmentLIHistoryAPI;
    @XmlAttribute(name = "schemaLocation")
    protected String schemaLocation;

    /**
     * Gets the value of the bayerCommitmentLIHistoryAPI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bayerCommitmentLIHistoryAPI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBayerCommitmentLIHistoryAPI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BayerCommitmentLIHistoryAPIType }
     * 
     * 
     */
    public List<BayerCommitmentLIHistoryAPIType> getBayerCommitmentLIHistoryAPI() {
        if (bayerCommitmentLIHistoryAPI == null) {
            bayerCommitmentLIHistoryAPI = new ArrayList<BayerCommitmentLIHistoryAPIType>();
        }
        return this.bayerCommitmentLIHistoryAPI;
    }

    /**
     * Gets the value of the schemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaLocation() {
        return schemaLocation;
    }

    /**
     * Sets the value of the schemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaLocation(String value) {
        this.schemaLocation = value;
    }

}
