//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:38:36 PM EDT 
//


package com.bayer.integration.rest.wbsread;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BayerWBSReadAPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerWBSReadAPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostObjectTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostObjectHierarchyLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ParentCostObjectHierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPDeleteFlagID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WBSPMOCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerWBSReadAPIType", propOrder = {
    "costObjectID",
    "costObjectName",
    "costObjectStatus",
    "costObjectTypeName",
    "costObjectHierarchyLevel",
    "parentCostObjectHierarchyPathID",
    "hierarchyPathID",
    "externalKey",
    "sapDeleteFlagID",
    "sapStatus",
    "wbspmoco"
})
public class BayerWBSReadAPIType {

    @XmlElement(name = "CostObjectID", required = true)
    protected String costObjectID;
    @XmlElement(name = "CostObjectName", required = true)
    protected String costObjectName;
    @XmlElement(name = "CostObjectStatus")
    protected String costObjectStatus;
    @XmlElement(name = "CostObjectTypeName")
    protected String costObjectTypeName;
    @XmlElement(name = "CostObjectHierarchyLevel")
    protected int costObjectHierarchyLevel;
    @XmlElement(name = "ParentCostObjectHierarchyPathID")
    protected String parentCostObjectHierarchyPathID;
    @XmlElement(name = "HierarchyPathID")
    protected String hierarchyPathID;
    @XmlElement(name = "ExternalKey")
    protected String externalKey;
    @XmlElement(name = "SAPDeleteFlagID")
    protected String sapDeleteFlagID;
    @XmlElement(name = "SAPStatus")
    protected String sapStatus;
    @XmlElement(name = "WBSPMOCO")
    protected String wbspmoco;

    /**
     * Gets the value of the costObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectID() {
        return costObjectID;
    }

    /**
     * Sets the value of the costObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectID(String value) {
        this.costObjectID = value;
    }

    /**
     * Gets the value of the costObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectName() {
        return costObjectName;
    }

    /**
     * Sets the value of the costObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectName(String value) {
        this.costObjectName = value;
    }

    /**
     * Gets the value of the costObjectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectStatus() {
        return costObjectStatus;
    }

    /**
     * Sets the value of the costObjectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectStatus(String value) {
        this.costObjectStatus = value;
    }

    /**
     * Gets the value of the costObjectTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectTypeName() {
        return costObjectTypeName;
    }

    /**
     * Sets the value of the costObjectTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectTypeName(String value) {
        this.costObjectTypeName = value;
    }

    /**
     * Gets the value of the costObjectHierarchyLevel property.
     * 
     */
    public int getCostObjectHierarchyLevel() {
        return costObjectHierarchyLevel;
    }

    /**
     * Sets the value of the costObjectHierarchyLevel property.
     * 
     */
    public void setCostObjectHierarchyLevel(int value) {
        this.costObjectHierarchyLevel = value;
    }

    /**
     * Gets the value of the parentCostObjectHierarchyPathID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentCostObjectHierarchyPathID() {
        return parentCostObjectHierarchyPathID;
    }

    /**
     * Sets the value of the parentCostObjectHierarchyPathID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentCostObjectHierarchyPathID(String value) {
        this.parentCostObjectHierarchyPathID = value;
    }

    /**
     * Gets the value of the hierarchyPathID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHierarchyPathID() {
        return hierarchyPathID;
    }

    /**
     * Sets the value of the hierarchyPathID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHierarchyPathID(String value) {
        this.hierarchyPathID = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the sapDeleteFlagID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPDeleteFlagID() {
        return sapDeleteFlagID;
    }

    /**
     * Sets the value of the sapDeleteFlagID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPDeleteFlagID(String value) {
        this.sapDeleteFlagID = value;
    }

    /**
     * Gets the value of the sapStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPStatus() {
        return sapStatus;
    }

    /**
     * Sets the value of the sapStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPStatus(String value) {
        this.sapStatus = value;
    }

    /**
     * Gets the value of the wbspmoco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBSPMOCO() {
        return wbspmoco;
    }

    /**
     * Sets the value of the wbspmoco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBSPMOCO(String value) {
        this.wbspmoco = value;
    }

}
