//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.01 at 03:09:38 PM EDT 
//


package com.bayer.integration.rest.project;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.project package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class PRJObjectFactory {

    private final static QName _BayerProjectAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerProjectAPI", "BayerProjectAPIRequest");
    private final static QName _BayerProjectAPIResult_QNAME = new QName("http://ecosys.net/api/BayerProjectAPI", "BayerProjectAPIResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.project
     * 
     */
    public PRJObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerProjectAPIResultType }
     * 
     */
    public BayerProjectAPIResultType createBayerProjectAPIResultType() {
        return new BayerProjectAPIResultType();
    }

    /**
     * Create an instance of {@link BayerProjectAPIRequestType }
     * 
     */
    public BayerProjectAPIRequestType createBayerProjectAPIRequestType() {
        return new BayerProjectAPIRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link BayerProjectAPIType }
     * 
     */
    public BayerProjectAPIType createBayerProjectAPIType() {
        return new BayerProjectAPIType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link PRJObjectResultType }
     * 
     */
    public PRJObjectResultType createObjectResultType() {
        return new PRJObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectAPI", name = "BayerProjectAPIRequest")
    public JAXBElement<BayerProjectAPIRequestType> createBayerProjectAPIRequest(BayerProjectAPIRequestType value) {
        return new JAXBElement<BayerProjectAPIRequestType>(_BayerProjectAPIRequest_QNAME, BayerProjectAPIRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectAPI", name = "BayerProjectAPIResult")
    public JAXBElement<BayerProjectAPIResultType> createBayerProjectAPIResult(BayerProjectAPIResultType value) {
        return new JAXBElement<BayerProjectAPIResultType>(_BayerProjectAPIResult_QNAME, BayerProjectAPIResultType.class, null, value);
    }

}
