//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.27 at 12:00:31 PM EDT 
//


package com.bayer.integration.rest.polco2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.polco2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BayerCommitmentLICOV2APIRequest_QNAME = new QName("http://ecosys.net/api/BayerCommitmentLICOV2API", "BayerCommitmentLICOV2APIRequest");
    private final static QName _BayerCommitmentLICOV2APIResult_QNAME = new QName("http://ecosys.net/api/BayerCommitmentLICOV2API", "BayerCommitmentLICOV2APIResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.polco2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerCommitmentLICOV2APIResultType }
     * 
     */
    public BayerCommitmentLICOV2APIResultType createBayerCommitmentLICOV2APIResultType() {
        return new BayerCommitmentLICOV2APIResultType();
    }

    /**
     * Create an instance of {@link BayerCommitmentLICOV2APIRequestType }
     * 
     */
    public BayerCommitmentLICOV2APIRequestType createBayerCommitmentLICOV2APIRequestType() {
        return new BayerCommitmentLICOV2APIRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link BayerCommitmentLICOV2APIType }
     * 
     */
    public BayerCommitmentLICOV2APIType createBayerCommitmentLICOV2APIType() {
        return new BayerCommitmentLICOV2APIType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCommitmentLICOV2APIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCommitmentLICOV2API", name = "BayerCommitmentLICOV2APIRequest")
    public JAXBElement<BayerCommitmentLICOV2APIRequestType> createBayerCommitmentLICOV2APIRequest(BayerCommitmentLICOV2APIRequestType value) {
        return new JAXBElement<BayerCommitmentLICOV2APIRequestType>(_BayerCommitmentLICOV2APIRequest_QNAME, BayerCommitmentLICOV2APIRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCommitmentLICOV2APIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCommitmentLICOV2API", name = "BayerCommitmentLICOV2APIResult")
    public JAXBElement<BayerCommitmentLICOV2APIResultType> createBayerCommitmentLICOV2APIResult(BayerCommitmentLICOV2APIResultType value) {
        return new JAXBElement<BayerCommitmentLICOV2APIResultType>(_BayerCommitmentLICOV2APIResult_QNAME, BayerCommitmentLICOV2APIResultType.class, null, value);
    }

}
