//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 04:29:45 PM GMT-04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/BayerPOPRHeadersV2API", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bayer.integration.rest.poprh2;
