//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 02:58:20 PM GMT 
//


package com.bayer.integration.rest.log;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.log package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class LogObjectFactory {

    private final static QName _IntegrationIssuesAPIResult_QNAME = new QName("http://ecosys.net/api/IntegrationIssuesAPI", "IntegrationIssuesAPIResult");
    private final static QName _IntegrationIssuesAPIRequest_QNAME = new QName("http://ecosys.net/api/IntegrationIssuesAPI", "IntegrationIssuesAPIRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.log
     * 
     */
    public LogObjectFactory() {
    }

    /**
     * Create an instance of {@link IntegrationIssuesAPIResultType }
     * 
     */
    public IntegrationIssuesAPIResultType createIntegrationIssuesAPIResultType() {
        return new IntegrationIssuesAPIResultType();
    }

    /**
     * Create an instance of {@link IntegrationIssuesAPIRequestType }
     * 
     */
    public IntegrationIssuesAPIRequestType createIntegrationIssuesAPIRequestType() {
        return new IntegrationIssuesAPIRequestType();
    }

    /**
     * Create an instance of {@link IntegrationIssuesAPIType }
     * 
     */
    public IntegrationIssuesAPIType createIntegrationIssuesAPIType() {
        return new IntegrationIssuesAPIType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegrationIssuesAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/IntegrationIssuesAPI", name = "IntegrationIssuesAPIResult")
    public JAXBElement<IntegrationIssuesAPIResultType> createIntegrationIssuesAPIResult(IntegrationIssuesAPIResultType value) {
        return new JAXBElement<IntegrationIssuesAPIResultType>(_IntegrationIssuesAPIResult_QNAME, IntegrationIssuesAPIResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegrationIssuesAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/IntegrationIssuesAPI", name = "IntegrationIssuesAPIRequest")
    public JAXBElement<IntegrationIssuesAPIRequestType> createIntegrationIssuesAPIRequest(IntegrationIssuesAPIRequestType value) {
        return new JAXBElement<IntegrationIssuesAPIRequestType>(_IntegrationIssuesAPIRequest_QNAME, IntegrationIssuesAPIRequestType.class, null, value);
    }

}
