package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 

* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Project_ActualsSet", propOrder = {
 "ControllingArea",
 "DocumentNo",
 "PostingRow",
 "Period",
 "PostingDate",
 "AmountTcurr",
 "AmountOcurr",
 "ObjectNo",
 "WbsElement",
 "PmOrder",
 "FiscalYear",
 "CostElement",
 "TransCurr",
 "ObjectCurr",
 "ExtrangeRate",
 "PurchOrd",
 "PurchOrdItem",
 "PurchSeq",
 "AcReferenceDoc",
 "AcHeaderTxt",
 "VendorId",
 "VendorName",
 "ProjectDefinition",
 "SystemId",
 "StartDate",
 "EndDate"
})

public class SapACTODataType {

@XmlElement(name = "WbsElement", required = true)
 protected String wbsElement;
@XmlElement(name = "PmOrderid", required = true)
protected String pmOrderid;
@XmlElement(name = "SystemId")
 protected String systemId;
 @XmlElement(name = "ProjectDefinition")
 protected String projectDefinition;
 @XmlElement(name = "ControllingArea")
 protected String controllingArea;
 @XmlElement(name = "DocumentNo")
 protected String documentNo;
 @XmlElement(name = "postingRow")
 protected String postingRow;
 @XmlElement(name = "Period")
 protected String period;
 @XmlElement(name = "PostingDate")
 protected XMLGregorianCalendar postingDate;
 @XmlElement(name = "AmountTcurr")
 protected Double amountTcurr;
 @XmlElement(name = "AmountOcurr")
 protected Double amountOcurr;
 @XmlElement(name = "ObjectNo")
 protected String objectNo;
 @XmlElement(name = "FiscalYear")
 protected String fiscalYear;
 @XmlElement(name = "CostElement")
 protected String costElement;
 @XmlElement(name = "TransCurr")
 protected String transCurr;
 @XmlElement(name = "ObjectCurr")
 protected String objectCurr;
 @XmlElement(name = "StartDate")
 protected XMLGregorianCalendar startDate;
 @XmlElement(name = "EndDate")
 protected XMLGregorianCalendar endDate;
 @XmlElement(name = "AcReferenceDoc")
 protected String acReferenceDoc;
 @XmlElement(name = "AcHeaderTxt")
 protected String acHeaderTxt;

	@XmlElement(name = "PurchOrd")
	 protected String purchOrd;
	 @XmlElement(name = "PurchOrdItem")
	 protected String purchOrdItem;
	 @XmlElement(name = "PurchOrdSeq")
	 protected String purchOrdSeq;
	 @XmlElement(name = "VendorId")
	 protected String vendorId;
	 @XmlElement(name = "VendorName")
	 protected String VendorName;
	 @XmlElement(name = "ExchangeRate")
	 protected Double exchangeRate;
 
 
 public String getWbsElement() {
		return wbsElement;
	}
	public void setWbsElement(String wbsElement) {
		this.wbsElement = wbsElement;
	}
	
	public String getPmOrderid() {
			return pmOrderid;
	}
	public void setPmOrderid(String pmOrderid) {
			this.pmOrderid = pmOrderid;
	}
	public String getSystemId() {
		return systemId;
	}
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}
	public String getProjectDefinition() {
		return projectDefinition;
	}
	public void setProjectDefinition(String projectDefinition) {
		this.projectDefinition = projectDefinition;
	}
	public String getControllingArea() {
		return controllingArea;
	}
	public void setControllingArea(String controllingArea) {
		this.controllingArea = controllingArea;
	}
	public String getDocumentNo() {
		return documentNo;
	}
	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}
	public String getPostingRow() {
		return postingRow;
	}
	public void setPostingRow(String postingRow) {
		this.postingRow = postingRow;
	}
	public String getPeriod() {
		return period;
	}
	public void setPeriod(String period) {
		this.period = period;
	}
	public XMLGregorianCalendar getPostingDate() {
		return postingDate;
	}
	public void setPostingDate(XMLGregorianCalendar postingDate) {
		this.postingDate = postingDate;
	}
	public Double getAmountTcurr() {
		return amountTcurr;
	}
	public void setAmountTcurr(Double amountTcurr) {
		this.amountTcurr = amountTcurr;
	}
	public Double getAmountOcurr() {
		return amountOcurr;
	}
	public void setAmountOcurr(Double amountOcurr) {
		this.amountOcurr = amountOcurr;
	}
	public String getObjectNo() {
		return objectNo;
	}
	public void setObjectNo(String objectNo) {
		this.objectNo = objectNo;
	}
	public String getFiscalYear() {
		return fiscalYear;
	}
	public void setFiscalYear(String fiscalYear) {
		this.fiscalYear = fiscalYear;
	}
	public String getCostElement() {
		return costElement;
	}
	public void setCostElement(String costElement) {
		this.costElement = costElement;
	}
	public String getTransCurr() {
		return transCurr;
	}
	public void setTransCurr(String transCurr) {
		this.transCurr = transCurr;
	}
	public String getObjectCurr() {
		return objectCurr;
	}
	public void setObjectCurr(String objectCurr) {
		this.objectCurr = objectCurr;
	}
	public XMLGregorianCalendar getStartDate() {
		return startDate;
	}
	public void setStartDate(XMLGregorianCalendar startDate) {
		this.startDate = startDate;
	}
	public XMLGregorianCalendar getEndDate() {
		return endDate;
	}
	public void setEndDate(XMLGregorianCalendar endDate) {
		this.endDate = endDate;
	}
	public String getAcReferenceDoc() {
			return acReferenceDoc;
	}
	public void setAcReferenceDoc(String acReferenceDoc) {
			this.acReferenceDoc = acReferenceDoc;
	}
	public String getAcHeaderTxt() {
			return acHeaderTxt;
	}
	public void setAcHeaderTxt(String acHeaderTxt) {
			this.acHeaderTxt = acHeaderTxt;
	}
	
	 public String getPurchOrd() {
			return purchOrd;
		}
		public void setPurchOrd(String purchOrd) {
			this.purchOrd = purchOrd;
		}
		public String getPurchOrdItem() {
			return purchOrdItem;
		}
		public void setPurchOrdItem(String purchOrdItem) {
			this.purchOrdItem = purchOrdItem;
		}
		public String getPurchOrdSeq() {
			return purchOrdSeq;
		}
		public void setPurchOrdSeq(String purchOrdSeq) {
			this.purchOrdSeq = purchOrdSeq;
		}
		public String getVendorId() {
			return vendorId;
		}
		public void setVendorId(String vendorId) {
			this.vendorId = vendorId;
		}
		public String getVendorName() {
			return VendorName;
		}
		public void setVendorName(String vendorName) {
			VendorName = vendorName;
		}
		public Double getExchangeRate() {
			return exchangeRate;
		}
		public void setExchangeRate(Double exchangeRate) {
			this.exchangeRate = exchangeRate;
		}
}

