package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="BayerWBSAPIType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectHierarchyLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
*         &lt;element name="ParentCostObjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="AccountAssignmentFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ObjectClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="LocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ResponsibleCostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="PersonResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ProjectTypeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectTypeInternalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="HierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchOrd_ItemSet", propOrder = {
 "PurchOrd",
 "PurchOrdItem",
 "PurchOrdSeq",
 "PurchOrdDesc",
 "WbsElement",
 "PmOrder",
 "PurchReq",
 "PurchReqItem",
 "CostElement",
 "CostElementDesc",
 "PoComCost",
 "PoActCost",
 "PoDocCurr",
 "ExchangeRate",
 "PoDate",
 "FinalConf",
 "DelFlag",
 "ProjectDefinition",
 "SystemId"
})

public class SapPOLODataType {
	
	@XmlElement(name = "PurchOrd", required = true)
	 protected String purchOrd;
	@XmlElement(name = "PurchOrdItem", required = true)
	 protected String purchOrdItem;
	 @XmlElement(name = "PurchOrdSeq")
	 protected String purchOrdSeq;
	 @XmlElement(name = "PurchOrdDesc")
	 protected String purchOrdDesc;
	 @XmlElement(name = "WbsElement", required = true)
	 protected String wbsElement;
	 @XmlElement(name = "PmOrder")
	 protected String pmOrder;
	 @XmlElement(name = "PurchReq")
	 protected String purReq;
	 @XmlElement(name = "PurchReqItem")
	 protected String purReqItem;
	 @XmlElement(name = "CostElement")
	 protected String costElement;
	 @XmlElement(name = "CostElementDesc")
	 protected String CostElementDesc;
	 @XmlElement(name = "PoComCost")
	 protected Double poComCost;
	 @XmlElement(name = "PoActCost")
	 protected Double poActCost;
	 @XmlElement(name = "PoDocCurr")
	 protected String poDocCurr;
	 @XmlElement(name = "ExchangeRate")
	 protected Double exchangeRate;
	 @XmlElement(name = "PoDate")
	 protected XMLGregorianCalendar poDate;
	 @XmlElement(name = "FinalConf")
	 protected String finalConf;
	 @XmlElement(name = "DelFlag")
	 protected String delFlag;
	 @XmlElement(name = "ProjectDefinition")
	 protected String projectDefinition;
	 @XmlElement(name = "SystemId", required = true)
	 protected String systemId;
	 
	
	
	public String getPurchOrd() {
		return purchOrd;
	}
	public void setPurchOrd(String purchOrd) {
		this.purchOrd = purchOrd;
	}
	public String getPurchOrdItem() {
		return purchOrdItem;
	}
	public void setPurchOrdItem(String purchOrdItem) {
		this.purchOrdItem = purchOrdItem;
	}
	public String getPurchOrdSeq() {
		return purchOrdSeq;
	}
	public void setPurchOrdSeq(String purchOrdSeq) {
		this.purchOrdSeq = purchOrdSeq;
	}
	public String getPurchOrdDesc() {
		return purchOrdDesc;
	}
	public void setPurchOrdDesc(String purchOrdDesc) {
		this.purchOrdDesc = purchOrdDesc;
	}
	public String getWbsElement() {
		return wbsElement;
	}
	public void setWbsElement(String wbsElement) {
		this.wbsElement = wbsElement;
	}
	public String getPmOrder() {
		return pmOrder;
	}
	public void setPmOrder(String pmOrder) {
		this.pmOrder = pmOrder;
	}
	public String getPurReq() {
		return purReq;
	}
	public void setPurReq(String purReq) {
		this.purReq = purReq;
	}
	public String getPurReqItem() {
		return purReqItem;
	}
	public void setPurReqItem(String purReqItem) {
		this.purReqItem = purReqItem;
	}
	public String getCostElement() {
		return costElement;
	}
	public void setCostElement(String costElement) {
		this.costElement = costElement;
	}
	public String getCostElementDesc() {
		return CostElementDesc;
	}
	public void setCostElementDesc(String costElementDesc) {
		CostElementDesc = costElementDesc;
	}
	public Double getPoComCost() {
		return poComCost;
	}
	public void setPoComCost(Double poComCost) {
		this.poComCost = poComCost;
	}
	public Double getPoActCost() {
		return poActCost;
	}
	public void setPoActCost(Double poActCost) {
		this.poActCost = poActCost;
	}
	public String getPoDocCurr() {
		return poDocCurr;
	}
	public void setPoDocCurr(String poDocCurr) {
		this.poDocCurr = poDocCurr;
	}
	public Double getExchangeRate() {
		return exchangeRate;
	}
	public void setExchangeRate(Double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}
	public XMLGregorianCalendar getPoDate() {
		return poDate;
	}
	public void setPoDate(XMLGregorianCalendar poDate) {
		this.poDate = poDate;
	}
	public String getFinalConf() {
		return finalConf;
	}
	public void setFinalConf(String finalConf) {
		this.finalConf = finalConf;
	}
	public String getDelFlag() {
		return delFlag;
	}
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
	public String getProjectDefinition() {
		return projectDefinition;
	}
	public void setProjectDefinition(String projectDefinition) {
		this.projectDefinition = projectDefinition;
	}
	public String getSystemId() {
		return systemId;
	}
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

}

