package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="BayerWBSAPIType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectHierarchyLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
*         &lt;element name="ParentCostObjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="AccountAssignmentFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ObjectClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="LocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ResponsibleCostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="PersonResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ProjectTypeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectTypeInternalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="HierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchOrd_HdrSet", propOrder = {
 "PurchOrd",
 "PurchOrdDesc",
 "PoComCost",
 "PoActCost",
 "PoDocCurr",
 "VendorId",
 "VendorName",
 "Requestor",
 "Receiver",
 "LastInvDt",
 "ProjectDefinition",
 "WbsElement",
 "PmOrderid",
 "SystemId"
})

public class SapPOHODataType {
	@XmlElement(name = "PurchOrd", required = true)
	 protected String purchOrd;
	 @XmlElement(name = "PurchOrdDesc")
	 protected String purchOrdDesc;
	 @XmlElement(name = "PoComCost")
	 protected Double poComCost;
	 @XmlElement(name = "PoActCost")
	 protected Double poActCost;
	 @XmlElement(name = "PoDocCurr")
	 protected String poDocCurr;
	 @XmlElement(name = "VendorId")
	 protected String vendorId;
	 @XmlElement(name = "VendorName")
	 protected String vendorName;
	 @XmlElement(name = "Requestor")
	 protected String requestor;
	 @XmlElement(name = "Receiver")
	 protected String receiver;
	 @XmlElement(name = "LastInvDt")
	 protected XMLGregorianCalendar lastInvDt;
	 @XmlElement(name = "ProjectDefinition")
	 protected String projectDefinition;
	 @XmlElement(name = "WbsElement")
	 protected String wbsElement;
	 @XmlElement(name = "PmOrderid")
	 protected String pmOrderid;
	 @XmlElement(name = "SystemId", required = true)
	 protected String systemId;
	 
 public String getPurchOrd() {
		return purchOrd;
	}
	public void setPurchOrd(String purchOrd) {
		this.purchOrd = purchOrd;
	}
	public String getPurchOrdDesc() {
		return purchOrdDesc;
	}
	public void setPurchOrdDesc(String purchOrdDesc) {
		this.purchOrdDesc = purchOrdDesc;
	}
	public Double getPoComCost() {
		return poComCost;
	}
	public void setPoComCost(Double poComCost) {
		this.poComCost = poComCost;
	}
	public Double getPoActCost() {
		return poActCost;
	}
	public void setPoActCost(Double poActCost) {
		this.poActCost = poActCost;
	}
	public String getPoDocCurr() {
		return poDocCurr;
	}
	public void setPoDocCurr(String poDocCurr) {
		this.poDocCurr = poDocCurr;
	}
	public String getVendorId() {
		return vendorId;
	}
	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}
	public String getVendorName() {
		return vendorName;
	}
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
	public String getRequestor() {
		return requestor;
	}
	public void setRequestor(String requestor) {
		this.requestor = requestor;
	}
	public String getReceiver() {
		return receiver;
	}
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}
	public XMLGregorianCalendar getLastInvDt() {
		return lastInvDt;
	}
	public void setLastInvDt(XMLGregorianCalendar lastInvDt) {
		this.lastInvDt = lastInvDt;
	}
	public String getProjectDefinition() {
		return projectDefinition;
	}
	public void setProjectDefinition(String projectDefinition) {
		this.projectDefinition = projectDefinition;
	}
	public String getWbsElement() {
		return wbsElement;
	}	
	public void setWbsElement(String wbsElement) {
		this.wbsElement = wbsElement;
	}
	public String getPmOrderid() {
		return pmOrderid;
	}
	public void setPmOrderid(String pmOrderid) {
		this.pmOrderid = pmOrderid;
	}
	public String getSystemId() {
		return systemId;
	}
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}
 
}

