package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="BayerWBSAPIType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectHierarchyLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
*         &lt;element name="ParentCostObjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="AccountAssignmentFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ObjectClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="LocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ResponsibleCostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="PersonResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ProjectTypeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectTypeInternalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="HierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WBS_OrderSet", propOrder = {
 "PmOrderid",
 "PmDescription",
 "PmEstCost",
 "PmActCost",
 "PmDocCur",
 "PmStatus",
 "WbsElement",
 "ProjectDefinition",
 "SystemId"
})

public class SapPMOODataType {

 @XmlElement(name = "WbsElement", required = true)
 protected String wbsElement;
 @XmlElement(name = "SystemId")
 protected String systemId;
 @XmlElement(name = "ProjectDefinition")
 protected String projectDefinition;
 @XmlElement(name = "PmOrderid", required = true)
 protected String pmOrderid;
 @XmlElement(name = "PmDescription")
 protected String pmDescription;
 @XmlElement(name = "PmEstCost")
 protected Double pmEstCost;
 @XmlElement(name = "PmActCost")
 protected Double pmActCost;
 @XmlElement(name = "PmDocCurr")
 protected String pmDocCurr;
 
 public String getWbsElement() {
	return wbsElement;
}
public void setWbsElement(String wbsElement) {
	this.wbsElement = wbsElement;
}
public String getSystemId() {
	return systemId;
}
public void setSystemId(String systemId) {
	this.systemId = systemId;
}
public String getProjectDefinition() {
	return projectDefinition;
}
public void setProjectDefinition(String projectDefinition) {
	this.projectDefinition = projectDefinition;
}
public String getPmOrderid() {
	return pmOrderid;
}
public void setPmOrderid(String pmOrderid) {
	this.pmOrderid = pmOrderid;
}
public String getPmDescription() {
	return pmDescription;
}
public void setPmDescription(String pmDescription) {
	this.pmDescription = pmDescription;
}
public Double getPmEstCost() {
	return pmEstCost;
}
public void setPmEstCost(Double pmEstCost) {
	this.pmEstCost = pmEstCost;
}
public Double getPmActCost() {
	return pmActCost;
}
public void setPmActCost(Double pmActCost) {
	this.pmActCost = pmActCost;
}
public String getPmDocCurr() {
	return pmDocCurr;
}
public void setPmDocCurr(String pmDocCurr) {
	this.pmDocCurr = pmDocCurr;
}
public String getPmStatus() {
	return pmStatus;
}
public void setPmStatus(String pmStatus) {
	this.pmStatus = pmStatus;
}
@XmlElement(name = "PmStatus")
 protected String pmStatus;


}

