package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 

* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchReq_ItemSet", propOrder = {
 "PurchReq",
 "PurchReqItem",
 "PurchReqSeq",
 "PurchReqDesc",
 "WbsElement",
 "PmOrder",
 "PurchOrd",
 "PurchOrdItem",
 "CostElement",
 "CostElementDesc",
 "PrComCost",
 "PrActCost",
 "PrDocCurr",
 "PrProjCurr",
 "ExchangeRate",
 "PrDate",
 "DeleteInd",
 "ProjectDefinition",
 "SystemId"
})

public class SapPRLODataType {
	@XmlElement(name = "PurchReq", required = true)
	 protected String purchReq;
	@XmlElement(name = "PurchReqItem", required = true)
	 protected String purchReqItem;
	 @XmlElement(name = "PurchReqSeq")
	 protected String purchReqSeq;
	 @XmlElement(name = "PurchOrdDesc")
	 protected String purchReqDesc;
	 @XmlElement(name = "WbsElement", required = true)
	 protected String wbsElement;
	 @XmlElement(name = "PmOrder")
	 protected String pmOrder;
	 @XmlElement(name = "PurchOrd")
	 protected String purOrd;
	 @XmlElement(name = "PurchOrdItem")
	 protected String purOrdItem;
	 @XmlElement(name = "CostElement")
	 protected String costElement;
	 @XmlElement(name = "CostElementDesc")
	 protected String CostElementDesc;
	 @XmlElement(name = "PrComCost")
	 protected Double prComCost;
	 @XmlElement(name = "PrActCost")
	 protected Double prActCost;
	 @XmlElement(name = "PrDocCurr")
	 protected String prDocCurr;
	 @XmlElement(name = "PrProjCurr")
	 protected String prProjCurr;
	 @XmlElement(name = "ExchangeRate")
	 protected Double exchangeRate;
	 @XmlElement(name = "PrDate")
	 protected XMLGregorianCalendar prDate;
	 @XmlElement(name = "DeleteInd")
	 protected String deleteInd;
	 @XmlElement(name = "ProjectDefinition")
	 protected String projectDefinition;
	 @XmlElement(name = "SystemId", required = true)
	 protected String systemId;
	 
	public String getPurchReq() {
		return purchReq;
	}
	public void setPurchReq(String purchReq) {
		this.purchReq = purchReq;
	}
	public String getPurchReqItem() {
		return purchReqItem;
	}
	public void setPurchReqItem(String purchReqItem) {
		this.purchReqItem = purchReqItem;
	}
	public String getPurchReqSeq() {
		return purchReqSeq;
	}
	public void setPurchReqSeq(String purchReqSeq) {
		this.purchReqSeq = purchReqSeq;
	}
	public String getPurchReqDesc() {
		return purchReqDesc;
	}
	public void setPurchReqDesc(String purchReqDesc) {
		this.purchReqDesc = purchReqDesc;
	}
	public String getWbsElement() {
		return wbsElement;
	}
	public void setWbsElement(String wbsElement) {
		this.wbsElement = wbsElement;
	}
	public String getPmOrder() {
		return pmOrder;
	}
	public void setPmOrder(String pmOrder) {
		this.pmOrder = pmOrder;
	}
	public String getPurOrd() {
		return purOrd;
	}
	public void setPurOrd(String purOrd) {
		this.purOrd = purOrd;
	}
	public String getPurOrdItem() {
		return purOrdItem;
	}
	public void setPurOrdItem(String purOrdItem) {
		this.purOrdItem = purOrdItem;
	}
	public String getCostElement() {
		return costElement;
	}
	public void setCostElement(String costElement) {
		this.costElement = costElement;
	}
	public String getCostElementDesc() {
		return CostElementDesc;
	}
	public void setCostElementDesc(String costElementDesc) {
		CostElementDesc = costElementDesc;
	}
	public Double getPrComCost() {
		return prComCost;
	}
	public void setPrComCost(Double prComCost) {
		this.prComCost = prComCost;
	}
	public Double getPrActCost() {
		return prActCost;
	}
	public void setPrActCost(Double prActCost) {
		this.prActCost = prActCost;
	}
	public String getPrDocCurr() {
		return prDocCurr;
	}
	public void setPrDocCurr(String prDocCurr) {
		this.prDocCurr = prDocCurr;
	}
	public String getPrProjCurr() {
		return prProjCurr;
	}
	public void setPrProjCurr(String prProjCurr) {
		this.prProjCurr = prProjCurr;
	}
	public Double getExchangeRate() {
		return exchangeRate;
	}
	public void setExchangeRate(Double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}
	public XMLGregorianCalendar getPrDate() {
		return prDate;
	}
	public void setPrDate(XMLGregorianCalendar prDate) {
		this.prDate = prDate;
	}
	public String getDeleteInd() {
		return deleteInd;
	}
	public void setDeleteInd(String deletInd) {
		this.deleteInd = deletInd;
	}
	public String getProjectDefinition() {
		return projectDefinition;
	}
	public void setProjectDefinition(String projectDefinition) {
		this.projectDefinition = projectDefinition;
	}
	public String getSystemId() {
		return systemId;
	}
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	 
}

