package com.bayer.integration.odata;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.11.13 at 10:26:17 PM EST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
* <p>Java class for BayerWBSAPIType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="BayerWBSAPIType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="CostObjectHierarchyLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
*         &lt;element name="ParentCostObjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="AccountAssignmentFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ObjectClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="LocationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ResponsibleCostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="PersonResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="ProjectTypeID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="CostObjectTypeInternalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="HierarchyPathID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WBS_ElementSet", propOrder = {
 "WbsElement",
 "SystemId",
 "WbsLevel",
 "ParentWbs",
 "ProjectDefinition",
 "Description",
 "ResponsibleNo",
 "ProfitCtr",
 "ProjType",
 "Currency",
 "ObjectClass",
 "DeletionFlag",
 "RespsblCcr",
 "Location"
})

public class SapWBSODataType {

 @XmlElement(name = "WbsElement", required = true)
 protected String wbsElement;
 @XmlElement(name = "SystemId", required = true)
 protected String systemId;
 @XmlElement(name = "WbsLevel")
 protected int wbsLevel;
 @XmlElement(name = "ParentWbs")
 protected String parentWbs;
 @XmlElement(name = "ProjectDefinition")
 protected String projectDefinition;
 @XmlElement(name = "Description")
 protected String description;
 @XmlElement(name = "ResponsibleNo")
 protected String responsibleNo;
 @XmlElement(name = "ProfitCtr")
 protected String ProfitCtr;
 @XmlElement(name = "ProjType")
 protected String projType;
 @XmlElement(name = "Currency")
 protected String currency;
 @XmlElement(name = "ObjectClass")
 protected String objectClass;
 @XmlElement(name = "DeletionFlag")
 protected String deletionFlag;
 @XmlElement(name = "RespsblCctr")
 protected String respsblCctr;
 @XmlElement(name = "Location")
 protected String location;
 @XmlElement(name = "hierarchyLevel")
 protected int hierarchyLevel;
 
 @XmlElement(name = "Status")
 protected String status;
 
 public String getWbsElement() {
	return wbsElement;
}
public void setWbsElement(String wbsElement) {
	this.wbsElement = wbsElement;
}
public String getSystemId() {
	return systemId;
}
public void setSystemId(String systemId) {
	this.systemId = systemId;
}
public int getWbsLevel() {
	return wbsLevel;
}
public void setWbsLevel(int wbsLevel) {
	this.wbsLevel = wbsLevel;
}
public String getParentWbs() {
	return parentWbs;
}
public void setParentWbs(String parentWbs) {
	this.parentWbs = parentWbs;
}
public String getProjectDefinition() {
	return projectDefinition;
}
public void setProjectDefinition(String projectDefinition) {
	this.projectDefinition = projectDefinition;
}
public String getDescription() {
	return description;
}
public void setDescription(String description) {
	this.description = description;
}
public String getResponsibleNo() {
	return responsibleNo;
}
public void setResponsibleNo(String responsibleNo) {
	this.responsibleNo = responsibleNo;
}
public String getProfitCtr() {
	return ProfitCtr;
}
public void setProfitCtr(String profitCtr) {
	ProfitCtr = profitCtr;
}
public String getProjType() {
	return projType;
}
public void setProjType(String projType) {
	this.projType = projType;
}
public String getCurrency() {
	return currency;
}
public void setCurrency(String currency) {
	  this.currency = currency;
}
public String getObjectClass() {
	return objectClass;
}
public void setObjectClass(String objectClass) {
	this.objectClass = objectClass;
}
public String getDeletionFlag() {
	return deletionFlag;
}
public void setDeletionFlag(String deletionFlag) {
	this.deletionFlag = deletionFlag;
}
public String getRespsblCctr() {
	return respsblCctr;
}
public void setRespsblCctr(String respsblCctr) {
	this.respsblCctr = respsblCctr;
}
public String getLocation() {
	return location;
}
public void setLocation(String location) {
	this.location = location;
}

public String getStatus() {
	return status;
}
public void setStatus(String status) {
	this.status = status;
}
public int getHierarchyLevel() {
	return hierarchyLevel;
}
public void setHierarchyLevel(int hierarchyLevel) {
	this.hierarchyLevel = hierarchyLevel;
}

}

