//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.19 at 12:33:59 AM GMT+01:00 
//


package com.bayer.integration.rest.pmordertran;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BayerPMOrderTranAPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerPMOrderTranAPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CostObjectExternalKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SAPWBSElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostTransactionCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CostCostObjectCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CurrencyTransactionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrencyCostObjectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VersionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ExternalKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AlternateCostTransactionCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CurrentTranFlagID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PeriodEndFlagID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerPMOrderTranAPIType", propOrder = {
    "costObjectExternalKey",
    "costObjectID",
    "costObjectName",
    "sapwbsElement",
    "costTransactionCurrency",
    "costCostObjectCurrency",
    "currencyTransactionCode",
    "currencyCostObjectCode",
    "versionID",
    "sapStatus",
    "transactionDate",
    "externalKey",
    "alternateCostTransactionCurrency",
    "currentTranFlagID",
    "periodEndFlagID"
})
public class BayerPMOrderTranAPIType {

    @XmlElement(name = "CostObjectExternalKey", required = true)
    protected String costObjectExternalKey;
    @XmlElement(name = "CostObjectID", required = true)
    protected String costObjectID;
    @XmlElement(name = "CostObjectName", required = true)
    protected String costObjectName;
    @XmlElement(name = "SAPWBSElement")
    protected String sapwbsElement;
    @XmlElement(name = "CostTransactionCurrency")
    protected Double costTransactionCurrency;
    @XmlElement(name = "CostCostObjectCurrency")
    protected Double costCostObjectCurrency;
    @XmlElement(name = "CurrencyTransactionCode", required = true)
    protected String currencyTransactionCode;
    @XmlElement(name = "CurrencyCostObjectCode")
    protected String currencyCostObjectCode;
    @XmlElement(name = "VersionID")
    protected String versionID;
    @XmlElement(name = "SAPStatus")
    protected String sapStatus;
    @XmlElement(name = "TransactionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar transactionDate;
    @XmlElement(name = "ExternalKey")
    protected String externalKey;
    @XmlElement(name = "AlternateCostTransactionCurrency")
    protected Double alternateCostTransactionCurrency;
    @XmlElement(name = "CurrentTranFlagID")
    protected String currentTranFlagID;
    @XmlElement(name = "PeriodEndFlagID")
    protected String periodEndFlagID;

    /**
     * Gets the value of the costObjectExternalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectExternalKey() {
        return costObjectExternalKey;
    }

    /**
     * Sets the value of the costObjectExternalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectExternalKey(String value) {
        this.costObjectExternalKey = value;
    }

    /**
     * Gets the value of the costObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectID() {
        return costObjectID;
    }

    /**
     * Sets the value of the costObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectID(String value) {
        this.costObjectID = value;
    }

    /**
     * Gets the value of the costObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectName() {
        return costObjectName;
    }

    /**
     * Sets the value of the costObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectName(String value) {
        this.costObjectName = value;
    }

    /**
     * Gets the value of the sapwbsElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPWBSElement() {
        return sapwbsElement;
    }

    /**
     * Sets the value of the sapwbsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPWBSElement(String value) {
        this.sapwbsElement = value;
    }

    /**
     * Gets the value of the costTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCostTransactionCurrency() {
        return costTransactionCurrency;
    }

    /**
     * Sets the value of the costTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCostTransactionCurrency(Double value) {
        this.costTransactionCurrency = value;
    }

    /**
     * Gets the value of the costCostObjectCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCostCostObjectCurrency() {
        return costCostObjectCurrency;
    }

    /**
     * Sets the value of the costCostObjectCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCostCostObjectCurrency(Double value) {
        this.costCostObjectCurrency = value;
    }

    /**
     * Gets the value of the currencyTransactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyTransactionCode() {
        return currencyTransactionCode;
    }

    /**
     * Sets the value of the currencyTransactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyTransactionCode(String value) {
        this.currencyTransactionCode = value;
    }

    /**
     * Gets the value of the currencyCostObjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCostObjectCode() {
        return currencyCostObjectCode;
    }

    /**
     * Sets the value of the currencyCostObjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCostObjectCode(String value) {
        this.currencyCostObjectCode = value;
    }

    /**
     * Gets the value of the versionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionID() {
        return versionID;
    }

    /**
     * Sets the value of the versionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionID(String value) {
        this.versionID = value;
    }

    /**
     * Gets the value of the sapStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPStatus() {
        return sapStatus;
    }

    /**
     * Sets the value of the sapStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPStatus(String value) {
        this.sapStatus = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionDate(XMLGregorianCalendar value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the alternateCostTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAlternateCostTransactionCurrency() {
        return alternateCostTransactionCurrency;
    }

    /**
     * Sets the value of the alternateCostTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlternateCostTransactionCurrency(Double value) {
        this.alternateCostTransactionCurrency = value;
    }

    /**
     * Gets the value of the currentTranFlagID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTranFlagID() {
        return currentTranFlagID;
    }

    /**
     * Sets the value of the currentTranFlagID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTranFlagID(String value) {
        this.currentTranFlagID = value;
    }

    /**
     * Gets the value of the periodEndFlagID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodEndFlagID() {
        return periodEndFlagID;
    }

    /**
     * Sets the value of the periodEndFlagID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodEndFlagID(String value) {
        this.periodEndFlagID = value;
    }

}
