//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 05:00:42 PM EST 
//


package com.bayer.integration.rest.projcplist;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.projcplist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BayerProjectCopyListAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerProjectCopyListAPI", "BayerProjectCopyListAPIRequest");
    private final static QName _BayerProjectCopyListAPIResult_QNAME = new QName("http://ecosys.net/api/BayerProjectCopyListAPI", "BayerProjectCopyListAPIResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.projcplist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerProjectCopyListAPIRequestType }
     * 
     */
    public BayerProjectCopyListAPIRequestType createBayerProjectCopyListAPIRequestType() {
        return new BayerProjectCopyListAPIRequestType();
    }

    /**
     * Create an instance of {@link BayerProjectCopyListAPIResultType }
     * 
     */
    public BayerProjectCopyListAPIResultType createBayerProjectCopyListAPIResultType() {
        return new BayerProjectCopyListAPIResultType();
    }

    /**
     * Create an instance of {@link BayerProjectCopyListAPIType }
     * 
     */
    public BayerProjectCopyListAPIType createBayerProjectCopyListAPIType() {
        return new BayerProjectCopyListAPIType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectCopyListAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectCopyListAPI", name = "BayerProjectCopyListAPIRequest")
    public JAXBElement<BayerProjectCopyListAPIRequestType> createBayerProjectCopyListAPIRequest(BayerProjectCopyListAPIRequestType value) {
        return new JAXBElement<BayerProjectCopyListAPIRequestType>(_BayerProjectCopyListAPIRequest_QNAME, BayerProjectCopyListAPIRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectCopyListAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectCopyListAPI", name = "BayerProjectCopyListAPIResult")
    public JAXBElement<BayerProjectCopyListAPIResultType> createBayerProjectCopyListAPIResult(BayerProjectCopyListAPIResultType value) {
        return new JAXBElement<BayerProjectCopyListAPIResultType>(_BayerProjectCopyListAPIResult_QNAME, BayerProjectCopyListAPIResultType.class, null, value);
    }

}
