//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 04:33:39 PM GMT 
//


package com.bayer.integration.rest.catg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.catg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BayerCreateVendorAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerCreateVendorAPI", "BayerCreateVendorAPIRequest");
    private final static QName _BayerCreateVendorAPIResult_QNAME = new QName("http://ecosys.net/api/BayerCreateVendorAPI", "BayerCreateVendorAPIResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.catg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerCreateVendorAPIResultType }
     * 
     */
    public BayerCreateVendorAPIResultType createBayerCreateVendorAPIResultType() {
        return new BayerCreateVendorAPIResultType();
    }

    /**
     * Create an instance of {@link BayerCreateVendorAPIRequestType }
     * 
     */
    public BayerCreateVendorAPIRequestType createBayerCreateVendorAPIRequestType() {
        return new BayerCreateVendorAPIRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link BayerCreateVendorAPIType }
     * 
     */
    public BayerCreateVendorAPIType createBayerCreateVendorAPIType() {
        return new BayerCreateVendorAPIType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCreateVendorAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCreateVendorAPI", name = "BayerCreateVendorAPIRequest")
    public JAXBElement<BayerCreateVendorAPIRequestType> createBayerCreateVendorAPIRequest(BayerCreateVendorAPIRequestType value) {
        return new JAXBElement<BayerCreateVendorAPIRequestType>(_BayerCreateVendorAPIRequest_QNAME, BayerCreateVendorAPIRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCreateVendorAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCreateVendorAPI", name = "BayerCreateVendorAPIResult")
    public JAXBElement<BayerCreateVendorAPIResultType> createBayerCreateVendorAPIResult(BayerCreateVendorAPIResultType value) {
        return new JAXBElement<BayerCreateVendorAPIResultType>(_BayerCreateVendorAPIResult_QNAME, BayerCreateVendorAPIResultType.class, null, value);
    }

}
