//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.19 at 04:12:03 PM GMT-04:00 
//


package com.bayer.integration.rest.polco;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BayerCommitmentLICOAPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerCommitmentLICOAPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentCostObjectExternalKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostObjectTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COParentChangedID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParentCOChangeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerCommitmentLICOAPIType", propOrder = {
    "parentCostObjectExternalKey",
    "costObjectID",
    "costObjectName",
    "costObjectStatus",
    "costObjectTypeName",
    "externalKey",
    "coParentChangedID",
    "parentCOChangeDate"
})
public class BayerCommitmentLICOAPIType {

    @XmlElement(name = "ParentCostObjectExternalKey")
    protected String parentCostObjectExternalKey;
    @XmlElement(name = "CostObjectID", required = true)
    protected String costObjectID;
    @XmlElement(name = "CostObjectName", required = true)
    protected String costObjectName;
    @XmlElement(name = "CostObjectStatus")
    protected String costObjectStatus;
    @XmlElement(name = "CostObjectTypeName")
    protected String costObjectTypeName;
    @XmlElement(name = "ExternalKey")
    protected String externalKey;
    @XmlElement(name = "COParentChangedID")
    protected String coParentChangedID;
    @XmlElement(name = "ParentCOChangeDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar parentCOChangeDate;

    /**
     * Gets the value of the parentCostObjectExternalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentCostObjectExternalKey() {
        return parentCostObjectExternalKey;
    }

    /**
     * Sets the value of the parentCostObjectExternalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentCostObjectExternalKey(String value) {
        this.parentCostObjectExternalKey = value;
    }

    /**
     * Gets the value of the costObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectID() {
        return costObjectID;
    }

    /**
     * Sets the value of the costObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectID(String value) {
        this.costObjectID = value;
    }

    /**
     * Gets the value of the costObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectName() {
        return costObjectName;
    }

    /**
     * Sets the value of the costObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectName(String value) {
        this.costObjectName = value;
    }

    /**
     * Gets the value of the costObjectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectStatus() {
        return costObjectStatus;
    }

    /**
     * Sets the value of the costObjectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectStatus(String value) {
        this.costObjectStatus = value;
    }

    /**
     * Gets the value of the costObjectTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectTypeName() {
        return costObjectTypeName;
    }

    /**
     * Sets the value of the costObjectTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectTypeName(String value) {
        this.costObjectTypeName = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the coParentChangedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOParentChangedID() {
        return coParentChangedID;
    }

    /**
     * Sets the value of the coParentChangedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOParentChangedID(String value) {
        this.coParentChangedID = value;
    }

    /**
     * Gets the value of the parentCOChangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getParentCOChangeDate() {
        return parentCOChangeDate;
    }

    /**
     * Sets the value of the parentCOChangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setParentCOChangeDate(XMLGregorianCalendar value) {
        this.parentCOChangeDate = value;
    }

}
