//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.27 at 07:58:40 PM GMT-04:00 
//


package com.bayer.integration.rest.accrual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BayerAccrualsAPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerAccrualsAPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CostObjectExternalKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostObjectID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SAPWBSElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostCostObjectCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CurrencyCostObjectCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CostTransactionCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CurrencyTransactionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostAccountID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CostAccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="FIDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommitmentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConversionRateCostObjectCurrency" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ExternalKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VersionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ControllingArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActualReferenceHeaderText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActualReferenceDoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OffsettingAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPPurchasingDocumentLineItemNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPUniqueID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SAPAccrualID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerAccrualsAPIType", propOrder = {
    "costObjectExternalKey",
    "costObjectID",
    "sapwbsElement",
    "costCostObjectCurrency",
    "currencyCostObjectCode",
    "costTransactionCurrency",
    "currencyTransactionCode",
    "costAccountID",
    "costAccountName",
    "transactionDate",
    "fiDocumentNumber",
    "commitmentID",
    "vendorID",
    "vendorName",
    "conversionRateCostObjectCurrency",
    "externalKey",
    "versionID",
    "controllingArea",
    "actualReferenceHeaderText",
    "actualReferenceDoc",
    "offsettingAccountNumber",
    "sapPurchasingDocumentLineItemNumber",
    "sapUniqueID",
    "sapAccrualID"
})
public class BayerAccrualsAPIType {

    @XmlElement(name = "CostObjectExternalKey", required = true)
    protected String costObjectExternalKey;
    @XmlElement(name = "CostObjectID", required = true)
    protected String costObjectID;
    @XmlElement(name = "SAPWBSElement")
    protected String sapwbsElement;
    @XmlElement(name = "CostCostObjectCurrency")
    protected Double costCostObjectCurrency;
    @XmlElement(name = "CurrencyCostObjectCode")
    protected String currencyCostObjectCode;
    @XmlElement(name = "CostTransactionCurrency")
    protected Double costTransactionCurrency;
    @XmlElement(name = "CurrencyTransactionCode", required = true)
    protected String currencyTransactionCode;
    @XmlElement(name = "CostAccountID", required = true)
    protected String costAccountID;
    @XmlElement(name = "CostAccountName", required = true)
    protected String costAccountName;
    @XmlElement(name = "TransactionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar transactionDate;
    @XmlElement(name = "FIDocumentNumber")
    protected String fiDocumentNumber;
    @XmlElement(name = "CommitmentID")
    protected String commitmentID;
    @XmlElement(name = "VendorID")
    protected String vendorID;
    @XmlElement(name = "VendorName")
    protected String vendorName;
    @XmlElement(name = "ConversionRateCostObjectCurrency")
    protected Double conversionRateCostObjectCurrency;
    @XmlElement(name = "ExternalKey")
    protected String externalKey;
    @XmlElement(name = "VersionID")
    protected String versionID;
    @XmlElement(name = "ControllingArea")
    protected String controllingArea;
    @XmlElement(name = "ActualReferenceHeaderText")
    protected String actualReferenceHeaderText;
    @XmlElement(name = "ActualReferenceDoc")
    protected String actualReferenceDoc;
    @XmlElement(name = "OffsettingAccountNumber")
    protected String offsettingAccountNumber;
    @XmlElement(name = "SAPPurchasingDocumentLineItemNumber")
    protected String sapPurchasingDocumentLineItemNumber;
    @XmlElement(name = "SAPUniqueID")
    protected String sapUniqueID;
    @XmlElement(name = "SAPAccrualID")
    protected String sapAccrualID;

    /**
     * Gets the value of the costObjectExternalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectExternalKey() {
        return costObjectExternalKey;
    }

    /**
     * Sets the value of the costObjectExternalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectExternalKey(String value) {
        this.costObjectExternalKey = value;
    }

    /**
     * Gets the value of the costObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostObjectID() {
        return costObjectID;
    }

    /**
     * Sets the value of the costObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostObjectID(String value) {
        this.costObjectID = value;
    }

    /**
     * Gets the value of the sapwbsElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPWBSElement() {
        return sapwbsElement;
    }

    /**
     * Sets the value of the sapwbsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPWBSElement(String value) {
        this.sapwbsElement = value;
    }

    /**
     * Gets the value of the costCostObjectCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCostCostObjectCurrency() {
        return costCostObjectCurrency;
    }

    /**
     * Sets the value of the costCostObjectCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCostCostObjectCurrency(Double value) {
        this.costCostObjectCurrency = value;
    }

    /**
     * Gets the value of the currencyCostObjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCostObjectCode() {
        return currencyCostObjectCode;
    }

    /**
     * Sets the value of the currencyCostObjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCostObjectCode(String value) {
        this.currencyCostObjectCode = value;
    }

    /**
     * Gets the value of the costTransactionCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCostTransactionCurrency() {
        return costTransactionCurrency;
    }

    /**
     * Sets the value of the costTransactionCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCostTransactionCurrency(Double value) {
        this.costTransactionCurrency = value;
    }

    /**
     * Gets the value of the currencyTransactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyTransactionCode() {
        return currencyTransactionCode;
    }

    /**
     * Sets the value of the currencyTransactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyTransactionCode(String value) {
        this.currencyTransactionCode = value;
    }

    /**
     * Gets the value of the costAccountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostAccountID() {
        return costAccountID;
    }

    /**
     * Sets the value of the costAccountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostAccountID(String value) {
        this.costAccountID = value;
    }

    /**
     * Gets the value of the costAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostAccountName() {
        return costAccountName;
    }

    /**
     * Sets the value of the costAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostAccountName(String value) {
        this.costAccountName = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransactionDate(XMLGregorianCalendar value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the fiDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIDocumentNumber() {
        return fiDocumentNumber;
    }

    /**
     * Sets the value of the fiDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIDocumentNumber(String value) {
        this.fiDocumentNumber = value;
    }

    /**
     * Gets the value of the commitmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitmentID() {
        return commitmentID;
    }

    /**
     * Sets the value of the commitmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitmentID(String value) {
        this.commitmentID = value;
    }

    /**
     * Gets the value of the vendorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorID(String value) {
        this.vendorID = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the conversionRateCostObjectCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConversionRateCostObjectCurrency() {
        return conversionRateCostObjectCurrency;
    }

    /**
     * Sets the value of the conversionRateCostObjectCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConversionRateCostObjectCurrency(Double value) {
        this.conversionRateCostObjectCurrency = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the versionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionID() {
        return versionID;
    }

    /**
     * Sets the value of the versionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionID(String value) {
        this.versionID = value;
    }

    /**
     * Gets the value of the controllingArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControllingArea() {
        return controllingArea;
    }

    /**
     * Sets the value of the controllingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControllingArea(String value) {
        this.controllingArea = value;
    }

    /**
     * Gets the value of the actualReferenceHeaderText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualReferenceHeaderText() {
        return actualReferenceHeaderText;
    }

    /**
     * Sets the value of the actualReferenceHeaderText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualReferenceHeaderText(String value) {
        this.actualReferenceHeaderText = value;
    }

    /**
     * Gets the value of the actualReferenceDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualReferenceDoc() {
        return actualReferenceDoc;
    }

    /**
     * Sets the value of the actualReferenceDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualReferenceDoc(String value) {
        this.actualReferenceDoc = value;
    }

    /**
     * Gets the value of the offsettingAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffsettingAccountNumber() {
        return offsettingAccountNumber;
    }

    /**
     * Sets the value of the offsettingAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffsettingAccountNumber(String value) {
        this.offsettingAccountNumber = value;
    }

    /**
     * Gets the value of the sapPurchasingDocumentLineItemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPPurchasingDocumentLineItemNumber() {
        return sapPurchasingDocumentLineItemNumber;
    }

    /**
     * Sets the value of the sapPurchasingDocumentLineItemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPPurchasingDocumentLineItemNumber(String value) {
        this.sapPurchasingDocumentLineItemNumber = value;
    }

    /**
     * Gets the value of the sapUniqueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPUniqueID() {
        return sapUniqueID;
    }

    /**
     * Sets the value of the sapUniqueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPUniqueID(String value) {
        this.sapUniqueID = value;
    }

    /**
     * Gets the value of the sapAccrualID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAPAccrualID() {
        return sapAccrualID;
    }

    /**
     * Sets the value of the sapAccrualID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAPAccrualID(String value) {
        this.sapAccrualID = value;
    }

}
