//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.09 at 01:15:15 PM EST 
//


package com.bayer.integration.rest.polprd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.polprd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class PlpdObjectFactory {

    private final static QName _BayerCommitmentLIPRDAPIResult_QNAME = new QName("http://ecosys.net/api/BayerCommitmentLIPRDAPI", "BayerCommitmentLIPRDAPIResult");
    private final static QName _BayerCommitmentLIPRDAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerCommitmentLIPRDAPI", "BayerCommitmentLIPRDAPIRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.polprd
     * 
     */
    public PlpdObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerCommitmentLIPRDAPIResultType }
     * 
     */
    public BayerCommitmentLIPRDAPIResultType createBayerCommitmentLIPRDAPIResultType() {
        return new BayerCommitmentLIPRDAPIResultType();
    }

    /**
     * Create an instance of {@link BayerCommitmentLIPRDAPIRequestType }
     * 
     */
    public BayerCommitmentLIPRDAPIRequestType createBayerCommitmentLIPRDAPIRequestType() {
        return new BayerCommitmentLIPRDAPIRequestType();
    }

    /**
     * Create an instance of {@link BayerCommitmentLIPRDAPIType }
     * 
     */
    public BayerCommitmentLIPRDAPIType createBayerCommitmentLIPRDAPIType() {
        return new BayerCommitmentLIPRDAPIType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link PlpdObjectResultType }
     * 
     */
    public PlpdObjectResultType createObjectResultType() {
        return new PlpdObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCommitmentLIPRDAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCommitmentLIPRDAPI", name = "BayerCommitmentLIPRDAPIResult")
    public JAXBElement<BayerCommitmentLIPRDAPIResultType> createBayerCommitmentLIPRDAPIResult(BayerCommitmentLIPRDAPIResultType value) {
        return new JAXBElement<BayerCommitmentLIPRDAPIResultType>(_BayerCommitmentLIPRDAPIResult_QNAME, BayerCommitmentLIPRDAPIResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerCommitmentLIPRDAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerCommitmentLIPRDAPI", name = "BayerCommitmentLIPRDAPIRequest")
    public JAXBElement<BayerCommitmentLIPRDAPIRequestType> createBayerCommitmentLIPRDAPIRequest(BayerCommitmentLIPRDAPIRequestType value) {
        return new JAXBElement<BayerCommitmentLIPRDAPIRequestType>(_BayerCommitmentLIPRDAPIRequest_QNAME, BayerCommitmentLIPRDAPIRequestType.class, null, value);
    }

}
