//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.19 at 12:33:59 AM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/BayerPMOrderTranAPI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bayer.integration.rest.pmordertran;
