//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.03 at 04:34:26 AM CEST 
//


package com.bayer.integration.rest.trancategory;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BayerTransactionCategoryAPIRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BayerTransactionCategoryAPIRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BayerTransactionCategoryAPI" type="{http://ecosys.net/api/BayerTransactionCategoryAPI}BayerTransactionCategoryAPIType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BayerTransactionCategoryAPIRequestType", propOrder = {
    "bayerTransactionCategoryAPI"
})
public class BayerTransactionCategoryAPIRequestType {

    @XmlElement(name = "BayerTransactionCategoryAPI")
    protected List<BayerTransactionCategoryAPIType> bayerTransactionCategoryAPI;
    @XmlAttribute(name = "schemaLocation")
    protected String schemaLocation;

    /**
     * Gets the value of the bayerTransactionCategoryAPI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bayerTransactionCategoryAPI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBayerTransactionCategoryAPI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BayerTransactionCategoryAPIType }
     * 
     * 
     */
    public List<BayerTransactionCategoryAPIType> getBayerTransactionCategoryAPI() {
        if (bayerTransactionCategoryAPI == null) {
            bayerTransactionCategoryAPI = new ArrayList<BayerTransactionCategoryAPIType>();
        }
        return this.bayerTransactionCategoryAPI;
    }

    /**
     * Gets the value of the schemaLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaLocation() {
        return schemaLocation;
    }

    /**
     * Sets the value of the schemaLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaLocation(String value) {
        this.schemaLocation = value;
    }

}
