//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.19 at 05:28:02 PM EDT 
//


package com.bayer.integration.rest.dco;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.dco package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class DCObjectFactory {

    private final static QName _BayerDirectChargeCOAPIResult_QNAME = new QName("http://ecosys.net/api/BayerDirectChargeCOAPI", "BayerDirectChargeCOAPIResult");
    private final static QName _BayerDirectChargeCOAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerDirectChargeCOAPI", "BayerDirectChargeCOAPIRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.dco
     * 
     */
    public DCObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerDirectChargeCOAPIResultType }
     * 
     */
    public BayerDirectChargeCOAPIResultType createBayerDirectChargeCOAPIResultType() {
        return new BayerDirectChargeCOAPIResultType();
    }

    /**
     * Create an instance of {@link BayerDirectChargeCOAPIRequestType }
     * 
     */
    public BayerDirectChargeCOAPIRequestType createBayerDirectChargeCOAPIRequestType() {
        return new BayerDirectChargeCOAPIRequestType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link BayerDirectChargeCOAPIType }
     * 
     */
    public BayerDirectChargeCOAPIType createBayerDirectChargeCOAPIType() {
        return new BayerDirectChargeCOAPIType();
    }

    /**
     * Create an instance of {@link DCObjectResultType }
     * 
     */
    public DCObjectResultType createObjectResultType() {
        return new DCObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerDirectChargeCOAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerDirectChargeCOAPI", name = "BayerDirectChargeCOAPIResult")
    public JAXBElement<BayerDirectChargeCOAPIResultType> createBayerDirectChargeCOAPIResult(BayerDirectChargeCOAPIResultType value) {
        return new JAXBElement<BayerDirectChargeCOAPIResultType>(_BayerDirectChargeCOAPIResult_QNAME, BayerDirectChargeCOAPIResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerDirectChargeCOAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerDirectChargeCOAPI", name = "BayerDirectChargeCOAPIRequest")
    public JAXBElement<BayerDirectChargeCOAPIRequestType> createBayerDirectChargeCOAPIRequest(BayerDirectChargeCOAPIRequestType value) {
        return new JAXBElement<BayerDirectChargeCOAPIRequestType>(_BayerDirectChargeCOAPIRequest_QNAME, BayerDirectChargeCOAPIRequestType.class, null, value);
    }

}
