//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.22 at 10:46:33 AM EST 
//


package com.bayer.integration.rest.projcpdrlist;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.projcpdrlist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BayerProjectCopyListForDRAPIResult_QNAME = new QName("http://ecosys.net/api/BayerProjectCopyListForDRAPI", "BayerProjectCopyListForDRAPIResult");
    private final static QName _BayerProjectCopyListForDRAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerProjectCopyListForDRAPI", "BayerProjectCopyListForDRAPIRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.projcpdrlist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerProjectCopyListForDRAPIRequestType }
     * 
     */
    public BayerProjectCopyListForDRAPIRequestType createBayerProjectCopyListForDRAPIRequestType() {
        return new BayerProjectCopyListForDRAPIRequestType();
    }

    /**
     * Create an instance of {@link BayerProjectCopyListForDRAPIResultType }
     * 
     */
    public BayerProjectCopyListForDRAPIResultType createBayerProjectCopyListForDRAPIResultType() {
        return new BayerProjectCopyListForDRAPIResultType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link BayerProjectCopyListForDRAPIType }
     * 
     */
    public BayerProjectCopyListForDRAPIType createBayerProjectCopyListForDRAPIType() {
        return new BayerProjectCopyListForDRAPIType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectCopyListForDRAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectCopyListForDRAPI", name = "BayerProjectCopyListForDRAPIResult")
    public JAXBElement<BayerProjectCopyListForDRAPIResultType> createBayerProjectCopyListForDRAPIResult(BayerProjectCopyListForDRAPIResultType value) {
        return new JAXBElement<BayerProjectCopyListForDRAPIResultType>(_BayerProjectCopyListForDRAPIResult_QNAME, BayerProjectCopyListForDRAPIResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerProjectCopyListForDRAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerProjectCopyListForDRAPI", name = "BayerProjectCopyListForDRAPIRequest")
    public JAXBElement<BayerProjectCopyListForDRAPIRequestType> createBayerProjectCopyListForDRAPIRequest(BayerProjectCopyListForDRAPIRequestType value) {
        return new JAXBElement<BayerProjectCopyListForDRAPIRequestType>(_BayerProjectCopyListForDRAPIRequest_QNAME, BayerProjectCopyListForDRAPIRequestType.class, null, value);
    }

}
