//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 10:22:26 PM GMT-04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ecosys.net/api/BayerCommitmentPOLITrackHistoryAPI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bayer.integration.rest.polth;
