//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.07 at 03:57:56 PM EST 
//


package com.bayer.integration.rest.actual;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bayer.integration.rest.actual package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BayerActualsAPIRequest_QNAME = new QName("http://ecosys.net/api/BayerActualsAPI", "BayerActualsAPIRequest");
    private final static QName _BayerActualsAPIResult_QNAME = new QName("http://ecosys.net/api/BayerActualsAPI", "BayerActualsAPIResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bayer.integration.rest.actual
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BayerActualsAPIRequestType }
     * 
     */
    public BayerActualsAPIRequestType createBayerActualsAPIRequestType() {
        return new BayerActualsAPIRequestType();
    }

    /**
     * Create an instance of {@link BayerActualsAPIResultType }
     * 
     */
    public BayerActualsAPIResultType createBayerActualsAPIResultType() {
        return new BayerActualsAPIResultType();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link DocumentValueType }
     * 
     */
    public DocumentValueType createDocumentValueType() {
        return new DocumentValueType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link BayerActualsAPIType }
     * 
     */
    public BayerActualsAPIType createBayerActualsAPIType() {
        return new BayerActualsAPIType();
    }

    /**
     * Create an instance of {@link ResultMessageType }
     * 
     */
    public ResultMessageType createResultMessageType() {
        return new ResultMessageType();
    }

    /**
     * Create an instance of {@link ObjectResultType }
     * 
     */
    public ObjectResultType createObjectResultType() {
        return new ObjectResultType();
    }

    /**
     * Create an instance of {@link DocumentLinkType }
     * 
     */
    public DocumentLinkType createDocumentLinkType() {
        return new DocumentLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerActualsAPIRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerActualsAPI", name = "BayerActualsAPIRequest")
    public JAXBElement<BayerActualsAPIRequestType> createBayerActualsAPIRequest(BayerActualsAPIRequestType value) {
        return new JAXBElement<BayerActualsAPIRequestType>(_BayerActualsAPIRequest_QNAME, BayerActualsAPIRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BayerActualsAPIResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ecosys.net/api/BayerActualsAPI", name = "BayerActualsAPIResult")
    public JAXBElement<BayerActualsAPIResultType> createBayerActualsAPIResult(BayerActualsAPIResultType value) {
        return new JAXBElement<BayerActualsAPIResultType>(_BayerActualsAPIResult_QNAME, BayerActualsAPIResultType.class, null, value);
    }

}
